//! Models for claude-mem observations (`~/.claude-mem/claude-mem.db`)
//!
//! claude-mem is an optional Claude Code plugin that captures tool use activity
//! and stores structured observations in a local SQLite database.
//!
//! Schema reference: observations table in claude-mem.db
//! - type values: discovery, decision, change, bugfix, feature, context (lowercase)
//! - title/subtitle: short summary generated by the LLM
//! - narrative: longer explanation

/// A single observation captured by claude-mem
#[derive(Debug, Clone)]
pub struct ClaudeMemObservation {
    pub id: i64,
    /// claude-mem internal session identifier
    pub memory_session_id: String,
    /// Observation type (lowercase): discovery, decision, change, bugfix, feature, context
    pub obs_type: String,
    /// Short title (LLM-generated)
    pub title: Option<String>,
    /// Longer explanation
    pub narrative: Option<String>,
    /// Project name / path
    pub project: String,
    /// ISO 8601 timestamp
    pub created_at: String,
}

impl ClaudeMemObservation {
    /// Emoji icon for the observation type
    pub fn icon(&self) -> &'static str {
        match self.obs_type.to_lowercase().as_str() {
            "discovery" => "🔍",
            "decision" => "◆",
            "change" => "✏",
            "bugfix" | "bug_fix" | "fix" => "✦",
            "feature" => "★",
            "context" => "○",
            _ => "·",
        }
    }

    /// Display label (capitalized type)
    pub fn type_label(&self) -> String {
        let mut chars = self.obs_type.chars();
        match chars.next() {
            None => String::new(),
            Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
        }
    }

    /// Best display text: title if available, else truncated narrative, else type
    pub fn display_text(&self) -> &str {
        if let Some(ref t) = self.title {
            if !t.is_empty() {
                return t.as_str();
            }
        }
        if let Some(ref n) = self.narrative {
            if !n.is_empty() {
                return n.as_str();
            }
        }
        self.obs_type.as_str()
    }
}
